name: 'Bar calling Foo Action'
description: ''
runs:
    using: "composite"
    steps:    
      - run: echo "${{ github.action_path }}"
        shell: bash

      - uses: fhammerl/action-path/foo-act@main
      - run: echo "${{ github.action_path }}"
        shell: bash
